library(R.utils)
library(data.table)
library(dplyr)
library(plyr)
require(treemap)
require(grid)
# Getting data from NOAA Weather events
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2")
bunzip2("repdata-data-StormData.csv.bz2","repdata-data-StormData.csv", remove = FALSE, skip = TRUE)
# Reading data
storm=fread("repdata-data-StormData.csv")
events=ddply(storm, .(EVTYPE),summarise,Fatalities = sum(FATALITIES),Injuries = sum(INJURIES))
economic=ddply(storm, .(EVTYPE),summarise,PROPDMG = sum(PROPDMG),CROPDMG = sum(CROPDMG))
# Question 1 - Answer using Treemaps!!!
vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)
svg('plot1.svg', width = 16, height = 9)
grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
treemap(storm,index="STATE",vSize="FATALITIES",vColor="FATALITIES",type="value",title = "Fatalities across US States", palette="RdGy",force.print.labels = TRUE,vp = vplayout(1,1))
treemap(storm,index="STATE",vSize="INJURIES",vColor="INJURIES",type="value",title = "Injuries across US States",palette="PRGn",force.print.labels = TRUE,vp = vplayout(1,2))
treemap(events,index="EVTYPE",vSize="Fatalities",vColor="Fatalities",type="value",title = "Fatalities by Weather Events", palette="RdPu",force.print.labels = TRUE,vp = vplayout(2,1))
treemap(events,index="EVTYPE",vSize="Injuries",vColor="Injuries",type="value",title = "Injuries by Weather Events",palette="RdBu",force.print.labels = TRUE,vp = vplayout(2,2))
dev.off()
# Question 2:
svg('plot2.svg', width = 16, height = 9)
grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
treemap(storm,index="STATE",vSize="PROPDMG",vColor="PROPDMG",type="value",title = "Property Damaged by weather across US States", palette="PuRd",force.print.labels = TRUE,vp = vplayout(1,1))
treemap(storm,index="STATE",vSize="CROPDMG",vColor="CROPDMG",type="value",title = "Crops Damaged by weather across US States", palette="BuGn",force.print.labels = TRUE,vp = vplayout(1,2))
treemap(economic,index="EVTYPE",vSize="PROPDMG",vColor="PROPDMG",type="value",title = "Property Damaged by Weather Events", palette="GnBu",force.print.labels = TRUE,vp = vplayout(2,1))
treemap(economic,index="EVTYPE",vSize="CROPDMG",vColor="CROPDMG",type="value",title = "Crops Damaged by Weather Events",palette="YlGn",force.print.labels = TRUE,vp = vplayout(2,2))
dev.off()